### ISSUE TITLE
Link to the changes required for Gerrit

### ISSUE THREAD

**Issue by sschuberth** [Ullink/gerrit-coverage-plugin#3]
I would be nice if the README contained a link to the changes required for Gerrit. If the changes were already sent upstream for review, please share the link so the community can more easily participate in the review process.

**Comment by sschuberth** [comment]
This information is available as part of [this Gerrit issue comment](https://code.google.com/p/gerrit/issues/detail?id=3538#c9) now, but it still would be nice to have it in  the README.

**Comment by gluck** [comment]
Agreed, will update the README with it
